// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-S2F9GQI
// DateTime: 5/24/2021 10:47:27 PM
// UserName: david
// Input file <TCCL.grammar.y - 5/24/2021 10:46:52 PM>

// options: no-lines diagnose & report gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace ASTBuilder
{
internal enum Token {error=2,EOF=3,AND=4,ASTERISK=5,BANG=6,
    BOOLEAN=7,CLASS=8,COLON=9,COMMA=10,ELSE=11,ASSIGN=12,
    HAT=13,IDENTIFIER=14,IF=15,INSTANCEOF=16,INT=17,INT_NUMBER=18,
    LBRACE=19,LBRACKET=20,LPAREN=21,MINUSOP=22,NEW=23,NULL=24,
    OP_EQ=25,OP_GE=26,OP_GT=27,OP_LAND=28,OP_LE=29,OP_LOR=30,
    OP_LT=31,OP_NE=32,PERCENT=33,PERIOD=34,PIPE=35,PLUSOP=36,
    PRIVATE=37,PUBLIC=38,QUESTION=39,RBRACE=40,RBRACKET=41,RETURN=42,
    RPAREN=43,RSLASH=44,SEMICOLON=45,STATIC=46,STRING_LITERAL=47,SUPER=48,
    STRUCT=49,THIS=50,TILDE=51,VOID=52,WHILE=53,UNARY=54};

// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal abstract class ScanBase : AbstractScanner<AbstractNode,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal class ScanObj {
  public int token;
  public AbstractNode yylval;
  public LexLocation yylloc;
  public ScanObj( int t, AbstractNode val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
internal partial class TCCLParser: ShiftReduceParser<AbstractNode, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[106];
  private static State[] states = new State[170];
  private static string[] nonTerms = new string[] {
      "CompilationUnit", "$accept", "ClassDeclaration", "Modifiers", "ClassBody", 
      "MemberDeclarations", "MemberDeclaration", "FieldDeclaration", "MethodDeclaration", 
      "ConstructorDeclaration", "StaticInitializer", "StructDeclaration", "TypeSpecifier", 
      "MethodSignature", "MethodBody", "ParameterList", "Parameter", "Block", 
      "FieldNames", "TypeName", "ArraySpecifier", "PrimitiveType", "QualifiedName", 
      "NameList", "LocalItems", "LocalItem", "LocalVariableDeclaration", "Statement", 
      "LocalVariableNames", "EmptyStatement", "ExpressionStatement", "SelectionStatement", 
      "IterationStatement", "ReturnStatement", "Expression", "ArgumentList", 
      "PrimaryExpression", "NotJustName", "SpecialName", "ComplexPrimary", "ComplexPrimaryNoParenthesis", 
      "Number", "FieldAccess", "MethodCall", "MethodReference", };

  static TCCLParser() {
    states[0] = new State(new int[]{38,116,37,117,46,118},new int[]{-1,1,-3,3,-4,4});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{8,5,38,113,37,114,46,115});
    states[5] = new State(new int[]{14,6});
    states[6] = new State(new int[]{19,8},new int[]{-5,7});
    states[7] = new State(-3);
    states[8] = new State(new int[]{40,168,38,116,37,117,46,162},new int[]{-6,9,-7,169,-8,12,-4,14,-9,164,-10,165,-11,166,-12,167});
    states[9] = new State(new int[]{40,10,38,116,37,117,46,162},new int[]{-7,11,-8,12,-4,14,-9,164,-10,165,-11,166,-12,167});
    states[10] = new State(-10);
    states[11] = new State(-13);
    states[12] = new State(new int[]{45,13});
    states[13] = new State(-14);
    states[14] = new State(new int[]{38,113,37,114,46,115,49,110,7,36,17,37,52,38,14,161},new int[]{-13,15,-14,159,-20,32,-22,35,-23,156,-21,107});
    states[15] = new State(new int[]{14,148},new int[]{-19,16,-14,17,-24,147});
    states[16] = new State(-27);
    states[17] = new State(new int[]{19,20},new int[]{-15,18,-18,19});
    states[18] = new State(-19);
    states[19] = new State(-25);
    states[20] = new State(new int[]{40,145,7,36,17,37,52,38,14,77,38,116,37,117,46,118,45,121,36,78,22,80,50,87,24,88,21,90,47,94,18,96,15,126,53,134,42,140,19,20},new int[]{-25,21,-26,146,-27,24,-13,25,-20,32,-22,35,-23,39,-21,107,-12,108,-4,109,-28,119,-30,120,-31,122,-35,123,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99,-32,125,-33,133,-34,139,-18,144});
    states[21] = new State(new int[]{40,22,7,36,17,37,52,38,14,77,38,116,37,117,46,118,45,121,36,78,22,80,50,87,24,88,21,90,47,94,18,96,15,126,53,134,42,140,19,20},new int[]{-26,23,-27,24,-13,25,-20,32,-22,35,-23,39,-21,107,-12,108,-4,109,-28,119,-30,120,-31,122,-35,123,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99,-32,125,-33,133,-34,139,-18,144});
    states[22] = new State(-41);
    states[23] = new State(-44);
    states[24] = new State(-45);
    states[25] = new State(new int[]{14,31},new int[]{-29,26,-24,28});
    states[26] = new State(new int[]{45,27});
    states[27] = new State(-47);
    states[28] = new State(new int[]{10,29,45,-49});
    states[29] = new State(new int[]{14,30});
    states[30] = new State(-38);
    states[31] = new State(-37);
    states[32] = new State(new int[]{20,33,14,-28});
    states[33] = new State(new int[]{41,34});
    states[34] = new State(-32);
    states[35] = new State(-30);
    states[36] = new State(-33);
    states[37] = new State(-34);
    states[38] = new State(-35);
    states[39] = new State(new int[]{34,40,12,42,20,-31,14,-31,45,-85,30,-85,28,-85,35,-85,13,-85,4,-85,25,-85,32,-85,27,-85,31,-85,29,-85,26,-85,36,-85,22,-85,5,-85,44,-85,33,-85,21,-99});
    states[40] = new State(new int[]{14,41});
    states[41] = new State(-102);
    states[42] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,43,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[43] = new State(new int[]{30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-65,43,-65,10,-65});
    states[44] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,45,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[45] = new State(new int[]{30,-66,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-66,43,-66,10,-66});
    states[46] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,47,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[47] = new State(new int[]{30,-67,28,-67,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-67,43,-67,10,-67});
    states[48] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,49,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[49] = new State(new int[]{30,-68,28,-68,35,-68,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-68,43,-68,10,-68});
    states[50] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,51,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[51] = new State(new int[]{30,-69,28,-69,35,-69,13,-69,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-69,43,-69,10,-69});
    states[52] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,53,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[53] = new State(new int[]{30,-70,28,-70,35,-70,13,-70,4,-70,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-70,43,-70,10,-70});
    states[54] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,55,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[55] = new State(new int[]{30,-71,28,-71,35,-71,13,-71,4,-71,25,-71,32,-71,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-71,43,-71,10,-71});
    states[56] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,57,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[57] = new State(new int[]{30,-72,28,-72,35,-72,13,-72,4,-72,25,-72,32,-72,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,45,-72,43,-72,10,-72});
    states[58] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,59,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[59] = new State(new int[]{30,-73,28,-73,35,-73,13,-73,4,-73,25,-73,32,-73,27,-73,31,-73,29,-73,26,-73,36,66,22,68,5,70,44,72,33,74,45,-73,43,-73,10,-73});
    states[60] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,61,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[61] = new State(new int[]{30,-74,28,-74,35,-74,13,-74,4,-74,25,-74,32,-74,27,-74,31,-74,29,-74,26,-74,36,66,22,68,5,70,44,72,33,74,45,-74,43,-74,10,-74});
    states[62] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,63,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[63] = new State(new int[]{30,-75,28,-75,35,-75,13,-75,4,-75,25,-75,32,-75,27,-75,31,-75,29,-75,26,-75,36,66,22,68,5,70,44,72,33,74,45,-75,43,-75,10,-75});
    states[64] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,65,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[65] = new State(new int[]{30,-76,28,-76,35,-76,13,-76,4,-76,25,-76,32,-76,27,-76,31,-76,29,-76,26,-76,36,66,22,68,5,70,44,72,33,74,45,-76,43,-76,10,-76});
    states[66] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,67,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[67] = new State(new int[]{30,-77,28,-77,35,-77,13,-77,4,-77,25,-77,32,-77,27,-77,31,-77,29,-77,26,-77,36,-77,22,-77,5,70,44,72,33,74,45,-77,43,-77,10,-77});
    states[68] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,69,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[69] = new State(new int[]{30,-78,28,-78,35,-78,13,-78,4,-78,25,-78,32,-78,27,-78,31,-78,29,-78,26,-78,36,-78,22,-78,5,70,44,72,33,74,45,-78,43,-78,10,-78});
    states[70] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,71,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[71] = new State(-81);
    states[72] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,73,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[73] = new State(-82);
    states[74] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,75,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[75] = new State(-83);
    states[76] = new State(new int[]{12,42,34,40,30,-85,28,-85,35,-85,13,-85,4,-85,25,-85,32,-85,27,-85,31,-85,29,-85,26,-85,36,-85,22,-85,5,-85,44,-85,33,-85,45,-85,43,-85,10,-85,21,-99});
    states[77] = new State(-101);
    states[78] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,79,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[79] = new State(-79);
    states[80] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,81,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[81] = new State(-80);
    states[82] = new State(-84);
    states[83] = new State(new int[]{34,84,45,-86,30,-86,28,-86,35,-86,13,-86,4,-86,25,-86,32,-86,27,-86,31,-86,29,-86,26,-86,36,-86,22,-86,5,-86,44,-86,33,-86,43,-86,10,-86});
    states[84] = new State(new int[]{14,85});
    states[85] = new State(-95);
    states[86] = new State(new int[]{34,-87,45,-87,30,-87,28,-87,35,-87,13,-87,4,-87,25,-87,32,-87,27,-87,31,-87,29,-87,26,-87,36,-87,22,-87,5,-87,44,-87,33,-87,43,-87,10,-87,21,-100});
    states[87] = new State(-103);
    states[88] = new State(-104);
    states[89] = new State(-88);
    states[90] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,91,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[91] = new State(new int[]{43,92,30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74});
    states[92] = new State(-89);
    states[93] = new State(new int[]{34,-90,45,-90,30,-90,28,-90,35,-90,13,-90,4,-90,25,-90,32,-90,27,-90,31,-90,29,-90,26,-90,36,-90,22,-90,5,-90,44,-90,33,-90,43,-90,10,-90,21,-98});
    states[94] = new State(-91);
    states[95] = new State(-92);
    states[96] = new State(-105);
    states[97] = new State(-93);
    states[98] = new State(-94);
    states[99] = new State(new int[]{21,100});
    states[100] = new State(new int[]{43,105,14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-36,101,-35,106,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[101] = new State(new int[]{43,102,10,103});
    states[102] = new State(-96);
    states[103] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,104,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[104] = new State(new int[]{30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,43,-64,10,-64});
    states[105] = new State(-97);
    states[106] = new State(new int[]{30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74,43,-63,10,-63});
    states[107] = new State(-29);
    states[108] = new State(-48);
    states[109] = new State(new int[]{49,110,38,113,37,114,46,115});
    states[110] = new State(new int[]{14,111});
    states[111] = new State(new int[]{19,8},new int[]{-5,112});
    states[112] = new State(-26);
    states[113] = new State(-7);
    states[114] = new State(-8);
    states[115] = new State(-9);
    states[116] = new State(-4);
    states[117] = new State(-5);
    states[118] = new State(-6);
    states[119] = new State(-46);
    states[120] = new State(-50);
    states[121] = new State(-56);
    states[122] = new State(-51);
    states[123] = new State(new int[]{45,124,30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74});
    states[124] = new State(-57);
    states[125] = new State(-52);
    states[126] = new State(new int[]{21,127});
    states[127] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,128,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[128] = new State(new int[]{43,129,30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74});
    states[129] = new State(new int[]{45,121,14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96,15,126,53,134,42,140,19,20},new int[]{-28,130,-30,120,-31,122,-35,123,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99,-32,125,-33,133,-34,139,-18,144});
    states[130] = new State(new int[]{11,131,40,-59,7,-59,17,-59,52,-59,14,-59,38,-59,37,-59,46,-59,45,-59,36,-59,22,-59,50,-59,24,-59,21,-59,47,-59,18,-59,15,-59,53,-59,42,-59,19,-59});
    states[131] = new State(new int[]{45,121,14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96,15,126,53,134,42,140,19,20},new int[]{-28,132,-30,120,-31,122,-35,123,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99,-32,125,-33,133,-34,139,-18,144});
    states[132] = new State(-58);
    states[133] = new State(-53);
    states[134] = new State(new int[]{21,135});
    states[135] = new State(new int[]{14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,136,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[136] = new State(new int[]{43,137,30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74});
    states[137] = new State(new int[]{45,121,14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96,15,126,53,134,42,140,19,20},new int[]{-28,138,-30,120,-31,122,-35,123,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99,-32,125,-33,133,-34,139,-18,144});
    states[138] = new State(-60);
    states[139] = new State(-54);
    states[140] = new State(new int[]{45,143,14,77,36,78,22,80,50,87,24,88,21,90,47,94,18,96},new int[]{-35,141,-23,76,-37,82,-38,83,-39,86,-40,89,-41,93,-42,95,-43,97,-44,98,-45,99});
    states[141] = new State(new int[]{45,142,30,44,28,46,35,48,13,50,4,52,25,54,32,56,27,58,31,60,29,62,26,64,36,66,22,68,5,70,44,72,33,74});
    states[142] = new State(-61);
    states[143] = new State(-62);
    states[144] = new State(-55);
    states[145] = new State(-42);
    states[146] = new State(-43);
    states[147] = new State(new int[]{10,29,45,-36});
    states[148] = new State(new int[]{21,149,10,-37,45,-37});
    states[149] = new State(new int[]{43,157,7,36,17,37,52,38,14,77},new int[]{-16,150,-17,158,-13,154,-20,32,-22,35,-23,156,-21,107});
    states[150] = new State(new int[]{43,151,10,152});
    states[151] = new State(-20);
    states[152] = new State(new int[]{7,36,17,37,52,38,14,77},new int[]{-17,153,-13,154,-20,32,-22,35,-23,156,-21,107});
    states[153] = new State(-23);
    states[154] = new State(new int[]{14,155});
    states[155] = new State(-24);
    states[156] = new State(new int[]{34,40,20,-31,14,-31});
    states[157] = new State(-21);
    states[158] = new State(-22);
    states[159] = new State(new int[]{19,20},new int[]{-18,160});
    states[160] = new State(-39);
    states[161] = new State(new int[]{21,149,34,-101,20,-101,14,-101});
    states[162] = new State(new int[]{19,20,38,-6,37,-6,46,-6,49,-6,7,-6,17,-6,52,-6,14,-6},new int[]{-18,163});
    states[163] = new State(-40);
    states[164] = new State(-15);
    states[165] = new State(-16);
    states[166] = new State(-17);
    states[167] = new State(-18);
    states[168] = new State(-11);
    states[169] = new State(-12);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,3});
    rules[2] = new Rule(-1, new int[]{-3});
    rules[3] = new Rule(-3, new int[]{-4,8,14,-5});
    rules[4] = new Rule(-4, new int[]{38});
    rules[5] = new Rule(-4, new int[]{37});
    rules[6] = new Rule(-4, new int[]{46});
    rules[7] = new Rule(-4, new int[]{-4,38});
    rules[8] = new Rule(-4, new int[]{-4,37});
    rules[9] = new Rule(-4, new int[]{-4,46});
    rules[10] = new Rule(-5, new int[]{19,-6,40});
    rules[11] = new Rule(-5, new int[]{19,40});
    rules[12] = new Rule(-6, new int[]{-7});
    rules[13] = new Rule(-6, new int[]{-6,-7});
    rules[14] = new Rule(-7, new int[]{-8,45});
    rules[15] = new Rule(-7, new int[]{-9});
    rules[16] = new Rule(-7, new int[]{-10});
    rules[17] = new Rule(-7, new int[]{-11});
    rules[18] = new Rule(-7, new int[]{-12});
    rules[19] = new Rule(-9, new int[]{-4,-13,-14,-15});
    rules[20] = new Rule(-14, new int[]{14,21,-16,43});
    rules[21] = new Rule(-14, new int[]{14,21,43});
    rules[22] = new Rule(-16, new int[]{-17});
    rules[23] = new Rule(-16, new int[]{-16,10,-17});
    rules[24] = new Rule(-17, new int[]{-13,14});
    rules[25] = new Rule(-15, new int[]{-18});
    rules[26] = new Rule(-12, new int[]{-4,49,14,-5});
    rules[27] = new Rule(-8, new int[]{-4,-13,-19});
    rules[28] = new Rule(-13, new int[]{-20});
    rules[29] = new Rule(-13, new int[]{-21});
    rules[30] = new Rule(-20, new int[]{-22});
    rules[31] = new Rule(-20, new int[]{-23});
    rules[32] = new Rule(-21, new int[]{-20,20,41});
    rules[33] = new Rule(-22, new int[]{7});
    rules[34] = new Rule(-22, new int[]{17});
    rules[35] = new Rule(-22, new int[]{52});
    rules[36] = new Rule(-19, new int[]{-24});
    rules[37] = new Rule(-24, new int[]{14});
    rules[38] = new Rule(-24, new int[]{-24,10,14});
    rules[39] = new Rule(-10, new int[]{-4,-14,-18});
    rules[40] = new Rule(-11, new int[]{46,-18});
    rules[41] = new Rule(-18, new int[]{19,-25,40});
    rules[42] = new Rule(-18, new int[]{19,40});
    rules[43] = new Rule(-25, new int[]{-26});
    rules[44] = new Rule(-25, new int[]{-25,-26});
    rules[45] = new Rule(-26, new int[]{-27});
    rules[46] = new Rule(-26, new int[]{-28});
    rules[47] = new Rule(-27, new int[]{-13,-29,45});
    rules[48] = new Rule(-27, new int[]{-12});
    rules[49] = new Rule(-29, new int[]{-24});
    rules[50] = new Rule(-28, new int[]{-30});
    rules[51] = new Rule(-28, new int[]{-31});
    rules[52] = new Rule(-28, new int[]{-32});
    rules[53] = new Rule(-28, new int[]{-33});
    rules[54] = new Rule(-28, new int[]{-34});
    rules[55] = new Rule(-28, new int[]{-18});
    rules[56] = new Rule(-30, new int[]{45});
    rules[57] = new Rule(-31, new int[]{-35,45});
    rules[58] = new Rule(-32, new int[]{15,21,-35,43,-28,11,-28});
    rules[59] = new Rule(-32, new int[]{15,21,-35,43,-28});
    rules[60] = new Rule(-33, new int[]{53,21,-35,43,-28});
    rules[61] = new Rule(-34, new int[]{42,-35,45});
    rules[62] = new Rule(-34, new int[]{42,45});
    rules[63] = new Rule(-36, new int[]{-35});
    rules[64] = new Rule(-36, new int[]{-36,10,-35});
    rules[65] = new Rule(-35, new int[]{-23,12,-35});
    rules[66] = new Rule(-35, new int[]{-35,30,-35});
    rules[67] = new Rule(-35, new int[]{-35,28,-35});
    rules[68] = new Rule(-35, new int[]{-35,35,-35});
    rules[69] = new Rule(-35, new int[]{-35,13,-35});
    rules[70] = new Rule(-35, new int[]{-35,4,-35});
    rules[71] = new Rule(-35, new int[]{-35,25,-35});
    rules[72] = new Rule(-35, new int[]{-35,32,-35});
    rules[73] = new Rule(-35, new int[]{-35,27,-35});
    rules[74] = new Rule(-35, new int[]{-35,31,-35});
    rules[75] = new Rule(-35, new int[]{-35,29,-35});
    rules[76] = new Rule(-35, new int[]{-35,26,-35});
    rules[77] = new Rule(-35, new int[]{-35,36,-35});
    rules[78] = new Rule(-35, new int[]{-35,22,-35});
    rules[79] = new Rule(-35, new int[]{36,-35});
    rules[80] = new Rule(-35, new int[]{22,-35});
    rules[81] = new Rule(-35, new int[]{-35,5,-35});
    rules[82] = new Rule(-35, new int[]{-35,44,-35});
    rules[83] = new Rule(-35, new int[]{-35,33,-35});
    rules[84] = new Rule(-35, new int[]{-37});
    rules[85] = new Rule(-37, new int[]{-23});
    rules[86] = new Rule(-37, new int[]{-38});
    rules[87] = new Rule(-38, new int[]{-39});
    rules[88] = new Rule(-38, new int[]{-40});
    rules[89] = new Rule(-40, new int[]{21,-35,43});
    rules[90] = new Rule(-40, new int[]{-41});
    rules[91] = new Rule(-41, new int[]{47});
    rules[92] = new Rule(-41, new int[]{-42});
    rules[93] = new Rule(-41, new int[]{-43});
    rules[94] = new Rule(-41, new int[]{-44});
    rules[95] = new Rule(-43, new int[]{-38,34,14});
    rules[96] = new Rule(-44, new int[]{-45,21,-36,43});
    rules[97] = new Rule(-44, new int[]{-45,21,43});
    rules[98] = new Rule(-45, new int[]{-41});
    rules[99] = new Rule(-45, new int[]{-23});
    rules[100] = new Rule(-45, new int[]{-39});
    rules[101] = new Rule(-23, new int[]{14});
    rules[102] = new Rule(-23, new int[]{-23,34,14});
    rules[103] = new Rule(-39, new int[]{50});
    rules[104] = new Rule(-39, new int[]{24});
    rules[105] = new Rule(-42, new int[]{18});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Token.error, (int)Token.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // CompilationUnit -> ClassDeclaration
{ CurrentSemanticValue = new CompilationUnit(ValueStack[ValueStack.Depth-1]);}
        break;
      case 3: // ClassDeclaration -> Modifiers, CLASS, IDENTIFIER, ClassBody
{ CurrentSemanticValue = new ClassDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]);}
        break;
      case 4: // Modifiers -> PUBLIC
{ CurrentSemanticValue = new Modifiers(ModifierType.PUBLIC);}
        break;
      case 5: // Modifiers -> PRIVATE
{ CurrentSemanticValue = new Modifiers(ModifierType.PRIVATE);}
        break;
      case 6: // Modifiers -> STATIC
{ CurrentSemanticValue = new Modifiers(ModifierType.STATIC);}
        break;
      case 7: // Modifiers -> Modifiers, PUBLIC
{ ((Modifiers)ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.PUBLIC); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 8: // Modifiers -> Modifiers, PRIVATE
{ ((Modifiers)ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.PRIVATE); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 9: // Modifiers -> Modifiers, STATIC
{ ((Modifiers)ValueStack[ValueStack.Depth-2]).AddModType(ModifierType.STATIC); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 10: // ClassBody -> LBRACE, MemberDeclarations, RBRACE
{ CurrentSemanticValue = new ClassBody(ValueStack[ValueStack.Depth-2]); }
        break;
      case 11: // ClassBody -> LBRACE, RBRACE
{ CurrentSemanticValue = new ClassBody(); }
        break;
      case 12: // MemberDeclarations -> MemberDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 13: // MemberDeclarations -> MemberDeclarations, MemberDeclaration
{ ValueStack[ValueStack.Depth-2].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 14: // MemberDeclaration -> FieldDeclaration, SEMICOLON
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 15: // MemberDeclaration -> MethodDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 16: // MemberDeclaration -> ConstructorDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 17: // MemberDeclaration -> StaticInitializer
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 18: // MemberDeclaration -> StructDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 19: // MethodDeclaration -> Modifiers, TypeSpecifier, MethodSignature, MethodBody
{CurrentSemanticValue = new MethodDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 20: // MethodSignature -> IDENTIFIER, LPAREN, ParameterList, RPAREN
{ CurrentSemanticValue = new MethodSignature(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 21: // MethodSignature -> IDENTIFIER, LPAREN, RPAREN
{ CurrentSemanticValue = new MethodSignature(ValueStack[ValueStack.Depth-3]); }
        break;
      case 22: // ParameterList -> Parameter
{ CurrentSemanticValue = new ParameterList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 23: // ParameterList -> ParameterList, COMMA, Parameter
{ ValueStack[ValueStack.Depth-3].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];}
        break;
      case 24: // Parameter -> TypeSpecifier, IDENTIFIER
{ CurrentSemanticValue = new Parameter(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 25: // MethodBody -> Block
{ CurrentSemanticValue = new MethodBody(ValueStack[ValueStack.Depth-1]); }
        break;
      case 26: // StructDeclaration -> Modifiers, STRUCT, IDENTIFIER, ClassBody
{ CurrentSemanticValue = new StructDeclaration(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 27: // FieldDeclaration -> Modifiers, TypeSpecifier, FieldNames
{ CurrentSemanticValue = new FieldDeclaration(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 28: // TypeSpecifier -> TypeName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 30: // TypeName -> PrimitiveType
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 31: // TypeName -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 33: // PrimitiveType -> BOOLEAN
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.BOOLEAN); }
        break;
      case 34: // PrimitiveType -> INT
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.INT); }
        break;
      case 35: // PrimitiveType -> VOID
{ CurrentSemanticValue = new PrimitiveType(EnumPrimitiveType.VOID); }
        break;
      case 36: // FieldNames -> NameList
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 37: // NameList -> IDENTIFIER
{ CurrentSemanticValue = new NameList(ValueStack[ValueStack.Depth-1]); }
        break;
      case 38: // NameList -> NameList, COMMA, IDENTIFIER
{ ValueStack[ValueStack.Depth-3].Child.makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];}
        break;
      case 39: // ConstructorDeclaration -> Modifiers, MethodSignature, Block
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 40: // StaticInitializer -> STATIC, Block
{ CurrentSemanticValue = new StaticInitializer(ValueStack[ValueStack.Depth-1]); }
        break;
      case 41: // Block -> LBRACE, LocalItems, RBRACE
{ CurrentSemanticValue = new Block(ValueStack[ValueStack.Depth-2]);}
        break;
      case 43: // LocalItems -> LocalItem
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 44: // LocalItems -> LocalItems, LocalItem
{ ValueStack[ValueStack.Depth-2].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 45: // LocalItem -> LocalVariableDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 46: // LocalItem -> Statement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 47: // LocalVariableDeclaration -> TypeSpecifier, LocalVariableNames, SEMICOLON
{ CurrentSemanticValue = new LocalVariableDeclaration(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2]); }
        break;
      case 48: // LocalVariableDeclaration -> StructDeclaration
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 49: // LocalVariableNames -> NameList
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 50: // Statement -> EmptyStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 51: // Statement -> ExpressionStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 52: // Statement -> SelectionStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 53: // Statement -> IterationStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 54: // Statement -> ReturnStatement
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 55: // Statement -> Block
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 56: // EmptyStatement -> SEMICOLON
{ CurrentSemanticValue = new Noop(); }
        break;
      case 57: // ExpressionStatement -> Expression, SEMICOLON
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 58: // SelectionStatement -> IF, LPAREN, Expression, RPAREN, Statement, ELSE, 
               //                       Statement
{ CurrentSemanticValue = new SelectionStatement(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 59: // SelectionStatement -> IF, LPAREN, Expression, RPAREN, Statement
{ CurrentSemanticValue = new SelectionStatement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 60: // IterationStatement -> WHILE, LPAREN, Expression, RPAREN, Statement
{ CurrentSemanticValue = new IterationStatement(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 61: // ReturnStatement -> RETURN, Expression, SEMICOLON
{ CurrentSemanticValue = new ReturnStatement(ValueStack[ValueStack.Depth-2]); }
        break;
      case 62: // ReturnStatement -> RETURN, SEMICOLON
{ CurrentSemanticValue = new ReturnStatement(); }
        break;
      case 63: // ArgumentList -> Expression
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];  }
        break;
      case 64: // ArgumentList -> ArgumentList, COMMA, Expression
{ ValueStack[ValueStack.Depth-3].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 65: // Expression -> QualifiedName, ASSIGN, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.ASSIGN, ValueStack[ValueStack.Depth-1]); }
        break;
      case 66: // Expression -> Expression, OP_LOR, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LOR, ValueStack[ValueStack.Depth-1]); }
        break;
      case 67: // Expression -> Expression, OP_LAND, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LOR, ValueStack[ValueStack.Depth-1]); }
        break;
      case 68: // Expression -> Expression, PIPE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PIPE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 69: // Expression -> Expression, HAT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.HAT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 70: // Expression -> Expression, AND, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.AND, ValueStack[ValueStack.Depth-1]); }
        break;
      case 71: // Expression -> Expression, OP_EQ, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_EQ, ValueStack[ValueStack.Depth-1]); }
        break;
      case 72: // Expression -> Expression, OP_NE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_NE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 73: // Expression -> Expression, OP_GT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_GT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 74: // Expression -> Expression, OP_LT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 75: // Expression -> Expression, OP_LE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_LE, ValueStack[ValueStack.Depth-1]); }
        break;
      case 76: // Expression -> Expression, OP_GE, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.OP_GT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 77: // Expression -> Expression, PLUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PLUSOP, ValueStack[ValueStack.Depth-1]); }
        break;
      case 78: // Expression -> Expression, MINUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.MINUSOP, ValueStack[ValueStack.Depth-1]); }
        break;
      case 79: // Expression -> PLUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-2], ExprKind.PLUSOP); }
        break;
      case 80: // Expression -> MINUSOP, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-2], ExprKind.MINUSOP); }
        break;
      case 81: // Expression -> Expression, ASTERISK, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.ASTERISK, ValueStack[ValueStack.Depth-1]); }
        break;
      case 82: // Expression -> Expression, RSLASH, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.RSLASH, ValueStack[ValueStack.Depth-1]); }
        break;
      case 83: // Expression -> Expression, PERCENT, Expression
{ CurrentSemanticValue = new Expression(ValueStack[ValueStack.Depth-3], ExprKind.PERCENT, ValueStack[ValueStack.Depth-1]); }
        break;
      case 84: // Expression -> PrimaryExpression
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 85: // PrimaryExpression -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 86: // PrimaryExpression -> NotJustName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 87: // NotJustName -> SpecialName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 88: // NotJustName -> ComplexPrimary
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 89: // ComplexPrimary -> LPAREN, Expression, RPAREN
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2];}
        break;
      case 90: // ComplexPrimary -> ComplexPrimaryNoParenthesis
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 91: // ComplexPrimaryNoParenthesis -> STRING_LITERAL
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 92: // ComplexPrimaryNoParenthesis -> Number
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 93: // ComplexPrimaryNoParenthesis -> FieldAccess
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 94: // ComplexPrimaryNoParenthesis -> MethodCall
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1];}
        break;
      case 95: // FieldAccess -> NotJustName, PERIOD, IDENTIFIER
{ ValueStack[ValueStack.Depth-3].makeSibling(ValueStack[ValueStack.Depth-1]); CurrentSemanticValue = ValueStack[ValueStack.Depth-3];}
        break;
      case 96: // MethodCall -> MethodReference, LPAREN, ArgumentList, RPAREN
{ CurrentSemanticValue = new MethodCall(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 97: // MethodCall -> MethodReference, LPAREN, RPAREN
{ CurrentSemanticValue = new MethodCall(ValueStack[ValueStack.Depth-3]); }
        break;
      case 98: // MethodReference -> ComplexPrimaryNoParenthesis
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 99: // MethodReference -> QualifiedName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 100: // MethodReference -> SpecialName
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 101: // QualifiedName -> IDENTIFIER
{ CurrentSemanticValue = new QualifiedName(ValueStack[ValueStack.Depth-1]); }
        break;
      case 102: // QualifiedName -> QualifiedName, PERIOD, IDENTIFIER
{ ValueStack[ValueStack.Depth-3].Child.makeSibling(ValueStack[ValueStack.Depth-1]);  CurrentSemanticValue = ValueStack[ValueStack.Depth-3]; }
        break;
      case 103: // SpecialName -> THIS
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 104: // SpecialName -> NULL
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
      case 105: // Number -> INT_NUMBER
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-1]; }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Token)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Token)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


}
}
